package edutech.project.serviceImpl;

import edutech.project.dto.request.ChangePasswordRequestDTO;
import edutech.project.dto.request.UserRequestDTO;
import edutech.project.dto.response.UserResponseDTO;
import edutech.project.exception.DuplicateResourceException;
import edutech.project.exception.ResourceNotFoundException;
import edutech.project.model.User;
import edutech.project.repository.UserRepo;
import edutech.project.service.UserService;
import edutech.project.util.CredentialGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import edutech.project.dto.response.BulkImportSummaryDTO;
import edutech.project.dto.response.BulkImportRowResultDTO;
import edutech.project.model.Role;
import edutech.project.util.ExcelHelper;
import org.apache.poi.ss.usermodel.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.transaction.annotation.Transactional;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

@Service
public class UserServiceImpl implements UserService {
    @Autowired
    private UserRepo userRepo;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private UserRowImporter userRowImporter;

    @Override
    public UserResponseDTO createUser(UserRequestDTO request) {
        if (userRepo.existsByEmail(request.getEmail())) {
            throw new DuplicateResourceException("Email already exists");
        }

        String username=request.getUsername();
        if (username==null || username.trim().isEmpty()) {
            String baseUsername=CredentialGenerator.generateUsername(request.getEmail());
            username=baseUsername;
            int count = 1;
            while (userRepo.existsByUsername(username)) {
                username = baseUsername + count;
                count++;
            }
        } else {
            if (userRepo.existsByUsername(username)) {
                throw new DuplicateResourceException("Username already exists");
            }
        }

        boolean autoGenerated=(request.getPassword()==null || request.getPassword().isBlank());
        String rawPassword=autoGenerated ? CredentialGenerator.generateTempPassword() : request.getPassword();

        User user=new User();
        user.setUsername(username);
        user.setPassword(passwordEncoder.encode(rawPassword));
        user.setEmail(request.getEmail());
        user.setRole(request.getRole());
        user.setMustChangePassword(true);
        User savedUser=userRepo.save(user);

        UserResponseDTO response=maptoResponse(savedUser);
        response.setTemporaryPassword(rawPassword);
        return response;
    }

    @Override
    public UserResponseDTO getUserById(Long userId) {
        User user=userRepo.findById(userId).orElseThrow(() -> new ResourceNotFoundException("User Not Found"));
        return maptoResponse(user);
    }

    @Override
    public List<UserResponseDTO> getAllUser(String query, String role) {
        List<User> users = userRepo.findAll();
        
        if (query != null && !query.isBlank()) {
            String q = query.trim().toLowerCase();
            users = users.stream().filter(u -> 
                (u.getUsername() != null && u.getUsername().toLowerCase().contains(q)) || 
                (u.getEmail() != null && u.getEmail().toLowerCase().contains(q))
            ).toList();
        }
        
        if (role != null && !role.isBlank() && !role.equalsIgnoreCase("ALL")) {
            users = users.stream().filter(u -> 
                u.getRole() != null && u.getRole().toString().equalsIgnoreCase(role)
            ).toList();
        }

        List<UserResponseDTO> response = new ArrayList<>();
        for (User user : users) {
            response.add(maptoResponse(user));
        }
        return response;
    }

    @Override
    public UserResponseDTO updateUser(Long userId, UserRequestDTO request) {
        User user=userRepo.findById(userId).orElseThrow(() -> new ResourceNotFoundException("User doesn't exist"));

        if (userRepo.existsByUsernameAndUserIdNot(request.getUsername(), userId)) {
            throw new DuplicateResourceException("Username already exists");
        }
        if (userRepo.existsByEmailAndUserIdNot(request.getEmail(), userId)) {
            throw new DuplicateResourceException("Email already exists");
        }

        user.setUsername(request.getUsername());
        user.setEmail(request.getEmail());
        user.setRole(request.getRole());
        
        if (request.getEnabled() != null) {
            user.setEnabled(request.getEnabled());
        }

        if (request.getPassword() != null && !request.getPassword().trim().isEmpty()) {
            user.setPassword(passwordEncoder.encode(request.getPassword().trim()));
            user.setMustChangePassword(true);
        }

        User updatedUser=userRepo.save(user);
        return maptoResponse(updatedUser);
    }

    @Override
    public void deleteUser(Long userId) {
        User user=userRepo.findById(userId).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        userRepo.delete(user);
    }

    @Override
    public void changePassword(User currentUser, ChangePasswordRequestDTO request) {
        if (!passwordEncoder.matches(request.getOldPassword(), currentUser.getPassword())) {
            throw new IllegalArgumentException("Current password is incorrect");
        }
        currentUser.setPassword(passwordEncoder.encode(request.getNewPassword()));
        currentUser.setMustChangePassword(false);
        userRepo.save(currentUser);
    }

    @Override
    public BulkImportSummaryDTO bulkImportUsers(MultipartFile file) {
        List<BulkImportRowResultDTO> results = new ArrayList<>();
        int success = 0, failure = 0;

        if (ExcelHelper.isExcelFile(file)) {
            try (InputStream is = file.getInputStream(); Workbook workbook = WorkbookFactory.create(is)) {
                Sheet sheet = workbook.getSheetAt(0);
                int lastRow = sheet.getLastRowNum();

                for (int i = 1; i <= lastRow; i++) {
                    Row row = sheet.getRow(i);
                    if (row == null){
                        continue;
                    }
                    int rowNumber = i + 1;
                    String name = ExcelHelper.readCell(row, 0);
                    String email = ExcelHelper.readCell(row, 1);
                    String roleStr = ExcelHelper.readCell(row, 2);

                    if (name == null || email == null || roleStr == null) {
                        results.add(BulkImportRowResultDTO.builder()
                                .rowNumber(rowNumber)
                                .success(false)
                                .message("Missing required cells in row " + rowNumber)
                                .build());
                        failure++;
                        continue;
                    }

                    try {
                        BulkImportRowResultDTO rowResult = userRowImporter.importRow(name, email, roleStr, rowNumber);
                        results.add(rowResult);
                        success++;
                    } catch (Exception ex) {
                        results.add(BulkImportRowResultDTO.builder()
                                .rowNumber(rowNumber)
                                .success(false)
                                .message(ex.getMessage())
                                .build());
                        failure++;
                    }
                }
            } catch (Exception e) {
                throw new IllegalArgumentException("Failed to read Excel file: " + e.getMessage());
            }
        } else {
            throw new IllegalArgumentException("Unsupported file type. Please upload a  Excel file.");
        }
        return BulkImportSummaryDTO.builder()
                .totalRows(results.size())
                .successCount(success)
                .failureCount(failure)
                .results(results)
                .build();
    }

    private UserResponseDTO maptoResponse(User user) {
        boolean complete = true;
        if (user.getRole() == edutech.project.model.Role.STUDENT && user.getStudent() == null) {
            complete = false;
        } else if (user.getRole() == edutech.project.model.Role.PROFESSOR && user.getProfessor() == null) {
            complete = false;
        }
        
        return UserResponseDTO.builder()
                .userId(user.getUserId())
                .username(user.getUsername())
                .email(user.getEmail())
                .role(user.getRole())
                .enabled(user.getEnabled())
                .mustChangePassword(user.getMustChangePassword())
                .profileComplete(complete)
                .build();
    }
}